[package]
name = "rep-indy-hash"
version = "0.2.0"
description = "Representationally Independent Hash for motoko"
repository = "https://github.com/skilesare/RepIndyHash.mo"
keywords = [ "hash", "icrc-3" ]
license = "MIT"

[dependencies]
core = "2.0.0"
sha2 = "0.1.12"
leb128 = "1.1.0"
test = "2.1.2"

[toolchain]
moc = "1.1.0"